"""add quiz explanations

Revision ID: 569b01ea479c
Revises: 8afb28b4a5ed
Create Date: 2026-09-11 09:36:29.722811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '569b01ea479c'
down_revision: Union[str, Sequence[str], None] = '8afb28b4a5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'quiz_questions',
    sa.Column('explanation', sa.String(length=1000), nullable=True)
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_questions', 'explanation')
    # ### end Alembic commands ###
